export const R = Object.freeze({
    ERROR_UNKNOWN: "Something went wrong",
    ERROR_USER_ALREADY_EXIST: "User already exist",
    ERROR_USERNAME_TAKEN: "Username already taken",
    ERROR_TOO_MANY_REQUESTS: "Blocked: Too many request.",
    INVALID_OTP: "Invalid OTP",
    ERROR_INVALID_CREDENTIAL: "Invalid credential",
    ERROR_UNAUTHORIZED: "Unauthorized access",
    STUDENT_ACCESS_RESTRICTION: "Only students are allowed",
    ERROR_INVALID_ADMIN_SECRET_KEY: "Invalid admin secret key",
    ERROR_PAYMENT_FAILED: "Payment failed",
    ERROR_PAYMENT_PENDING: "Payment pending",
    ERROR_FILE_NOT_FOUND: "File not found",
    ERROR_INSTITUTE_NOT_FOUND: "Institute not found",
    ERROR_PAYMENT_NOT_FOUND: "Payment not found",
    ERROR_PASSWORD_NOT_MATCH: "Password not match",
});
